# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BatchRemove.proto
# Protobuf Python Version: 6.33.1
# Created By @ShamNpl don't remove credit otherwise Fuck your mother/sister 🤫
# Creator main channel @FFbotsALL

"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'BatchRemove.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# Created By @ShamNpl don't remove credit otherwise Fuck your mother/sister 🤫
# Creator main channel @FFbotsALL


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x42\x61tchRemove.proto\x12\x05proto\"?\n\x12\x43SGetFriendListReq\x12\x15\n\rneed_presence\x18\x01 \x01(\x08\x12\x12\n\nneed_stats\x18\x02 \x01(\x08\"2\n\nFriendInfo\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x10\n\x08nickname\x18\x03 \x01(\t\"8\n\x12\x43SGetFriendListRes\x12\"\n\x07\x66riends\x18\x01 \x03(\x0b\x32\x11.proto.FriendInfo\".\n\x16\x43SBatchRemoveFriendReq\x12\x14\n\x0cremovee_list\x18\x01 \x03(\x04\"C\n\x16\x43SBatchRemoveFriendRes\x12\x14\n\x0cremovee_list\x18\x01 \x03(\x04\x12\x13\n\x0block_region\x18\x02 \x01(\tb\x06proto3')

# Created By @ShamNpl don't remove credit otherwise Fuck your mother/sister 🤫
# Creator main channel @FFbotsALL

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BatchRemove_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSGETFRIENDLISTREQ']._serialized_start=28
  _globals['_CSGETFRIENDLISTREQ']._serialized_end=91
  _globals['_FRIENDINFO']._serialized_start=93
  _globals['_FRIENDINFO']._serialized_end=143
  _globals['_CSGETFRIENDLISTRES']._serialized_start=145
  _globals['_CSGETFRIENDLISTRES']._serialized_end=201
  _globals['_CSBATCHREMOVEFRIENDREQ']._serialized_start=203
  _globals['_CSBATCHREMOVEFRIENDREQ']._serialized_end=249
  _globals['_CSBATCHREMOVEFRIENDRES']._serialized_start=251
  _globals['_CSBATCHREMOVEFRIENDRES']._serialized_end=318
# @@protoc_insertion_point(module_scope)

# Created By @ShamNpl don't remove credit otherwise Fuck your mother/sister 🤫
# Creator main channel @FFbotsALL